export interface Bank {
  id: string;
  name: string;
  shortName: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  textOnPrimary: string;
  bgLight: string;
  logoText: string;
  logoInitials: string;
}

export const BANKS: Bank[] = [
  {
    id: "indusind",
    name: "IndusInd Bank",
    shortName: "IndusInd",
    primaryColor: "#1A1A2E",
    secondaryColor: "#12122A",
    accentColor: "#E4002B",
    textOnPrimary: "#FFFFFF",
    bgLight: "#EAEAF5",
    logoText: "IndusInd Bank",
    logoInitials: "IIB",
  },
  {
    id: "yesbank",
    name: "Yes Bank",
    shortName: "Yes Bank",
    primaryColor: "#0066B3",
    secondaryColor: "#004E8A",
    accentColor: "#00AEEF",
    textOnPrimary: "#FFFFFF",
    bgLight: "#E5F3FC",
    logoText: "Yes Bank",
    logoInitials: "YES",
  },
  {
    id: "axis",
    name: "Axis Bank",
    shortName: "Axis",
    primaryColor: "#97144D",
    secondaryColor: "#7A0F3E",
    accentColor: "#12877F",
    textOnPrimary: "#FFFFFF",
    bgLight: "#FCE8F0",
    logoText: "Axis Bank",
    logoInitials: "AXIS",
  },
  {
    id: "bobcard",
    name: "BobCard",
    shortName: "BobCard",
    primaryColor: "#E35B18",
    secondaryColor: "#C24C12",
    accentColor: "#1E3A5F",
    textOnPrimary: "#FFFFFF",
    bgLight: "#FEF0E9",
    logoText: "BobCard",
    logoInitials: "BOB",
  },
  {
    id: "sbicard",
    name: "SBICard",
    shortName: "SBICard",
    primaryColor: "#1B4F9B",
    secondaryColor: "#0D3378",
    accentColor: "#F5A623",
    textOnPrimary: "#FFFFFF",
    bgLight: "#EBF2FF",
    logoText: "SBICard",
    logoInitials: "SBIC",
  },
  {
    id: "hdfc",
    name: "HDFC Bank",
    shortName: "HDFC",
    primaryColor: "#004C8F",
    secondaryColor: "#003670",
    accentColor: "#E31837",
    textOnPrimary: "#FFFFFF",
    bgLight: "#E8F0FB",
    logoText: "HDFC Bank",
    logoInitials: "HDFC",
  },
  {
    id: "kotak",
    name: "Kotak Mahindra Bank",
    shortName: "Kotak",
    primaryColor: "#ED1C24",
    secondaryColor: "#C41730",
    accentColor: "#231F20",
    textOnPrimary: "#FFFFFF",
    bgLight: "#FFF0F0",
    logoText: "Kotak Mahindra Bank",
    logoInitials: "KMB",
  },
  {
    id: "federal",
    name: "Federal Bank",
    shortName: "Federal",
    primaryColor: "#0A3172",
    secondaryColor: "#072458",
    accentColor: "#F5A623",
    textOnPrimary: "#FFFFFF",
    bgLight: "#E6ECF8",
    logoText: "Federal Bank",
    logoInitials: "FED",
  },
  {
    id: "aubank",
    name: "AU Small Finance Bank",
    shortName: "AU Bank",
    primaryColor: "#E31837",
    secondaryColor: "#B8122C",
    accentColor: "#1C5FA8",
    textOnPrimary: "#FFFFFF",
    bgLight: "#FDECEA",
    logoText: "AU Small Finance Bank",
    logoInitials: "AU",
  },
  {
    id: "dbs",
    name: "DBS Bank",
    shortName: "DBS",
    primaryColor: "#E50026",
    secondaryColor: "#B8001E",
    accentColor: "#000000",
    textOnPrimary: "#FFFFFF",
    bgLight: "#FDECEA",
    logoText: "DBS Bank",
    logoInitials: "DBS",
  },
  {
    id: "ltfinance",
    name: "L&T Finance",
    shortName: "L&T Finance",
    primaryColor: "#00693E",
    secondaryColor: "#005230",
    accentColor: "#F5A623",
    textOnPrimary: "#FFFFFF",
    bgLight: "#E6F4EF",
    logoText: "L&T Finance",
    logoInitials: "LTF",
  },
  {
    id: "smfg",
    name: "SMFG India Credit",
    shortName: "SMFG",
    primaryColor: "#682F8D",
    secondaryColor: "#512370",
    accentColor: "#F5A623",
    textOnPrimary: "#FFFFFF",
    bgLight: "#F3EAF9",
    logoText: "SMFG India Credit",
    logoInitials: "SMFG",
  },
  {
    id: "bajajfinance",
    name: "Bajaj Finance",
    shortName: "Bajaj Fin.",
    primaryColor: "#003399",
    secondaryColor: "#00267A",
    accentColor: "#F5A623",
    textOnPrimary: "#FFFFFF",
    bgLight: "#E6ECFF",
    logoText: "Bajaj Finance",
    logoInitials: "BFL",
  },
  {
    id: "other",
    name: "Other",
    shortName: "Other",
    primaryColor: "#4B5563",
    secondaryColor: "#374151",
    accentColor: "#6366F1",
    textOnPrimary: "#FFFFFF",
    bgLight: "#F3F4F6",
    logoText: "Other",
    logoInitials: "OTH",
  },
];

export function getBankById(id: string): Bank | undefined {
  return BANKS.find((b) => b.id === id);
}
